services:
  api:
    build:
      context: .
    image: michibiki/mx-api:0.1.0
    restart: always
    env_file:
      - ./dev/.env
    environment:
      MX_API_CONFIG: /etc/mx-api/configs/config.yaml
    ports:
      - "8080:8080"
    volumes:
      - ./configs:/etc/mx-api/configs:ro

  frontend:
    image: nginx:1.29-alpine
    depends_on:
      - api
    ports:
      - "5173:80"
    volumes:
      - ./dev/frontend:/usr/share/nginx/html:ro
